# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 788856093581ea7543df3b58cb03451beaa2c7ef58b49084456b23abc942664f6d114b71d280d74dd999d47ab5f4487b4132aac3a515213e6fb6179955af879a

test:
  secret_key_base: 13b748204b5cebee791c1b45ca4b1daaf57d35e18434159233c62517bb53612c8f6025432c39f1fb5abb452520d189f2027a335f919ca7b2e39746323a3ce0f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
